### ISSUE TITLE
复现遇到问题

### ISSUE THREAD

**Issue by tbatmmx** [tgg-77/TDFusion#1]
您好，我在复现您的代码时，发现并无训练数据，但是论文中说是对三个公开数据集进行了合并，请问是全部合并还是选择性的合并呢。
第二点是，我在代码中并没有找到某一部分说 数据加载是按照三个不同模态的数据进行加载，仅仅找到了image_set_ir的加载

**Comment by tgg-77** [comment]
我们的训练过程是采用coco14数据集进行的，不需要对红外和可见数据进行训练。加载问题应该是训练过程的加载是单模态，测试阶段是三模态。
